on:
  push:
    tags:
      - 'v*'

name: Create draft release

jobs:
  build:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.4.0
        with:
          node-version: 10.x
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Test
        run: |
          npm run test:coverage
        env:
          CI: true
      - name: Bundle
        run: |
          npm run bundle:library
          npm run bundle:app
          npm run vdldoc
      - name: Create draft release
        id: create_release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload component bundle
        id: upload-component-bundle
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/vdlx-datagrid.zip
          asset_name: vdlx-datagrid.zip
          asset_content_type: application/zip
      - name: Upload app
        id: upload-app
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/vdlx-datagrid-examples-app.zip
          asset_name: vdlx-datagrid-examples-app.zip
          asset_content_type: application/zip
      - name: Update VDLDoc reference
        uses: docker://decathlon/wiki-page-creator-action:2.0.1
        env:
          GH_PAT: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
          ACTION_MAIL: 13833731+timhemming-fico@users.noreply.github.com
          ACTION_NAME: timhemming-fico
          OWNER: fico-xpress
          REPO_NAME: vdlx-datagrid
          MD_FOLDER: target
